 # Filename: Makefile
 # Author: Chao Huang, Yeung-Kit Wong
 # Date: Aug 23 2016
 # Description: 

CC=g++
CXXFLAGS=-std=c++11 -g -Wall -gdwarf-2
LDFLAGS=-g

all: pathfinder ActorGraph.o

ActorGraph.o: ActorGraph.hpp

clean:
	rm -f *.o core* *~
